### ISSUE TITLE
Scores & Feedback

### ISSUE THREAD

**Issue by ssvillarosa** [PUP-BSIT/exercise-4-devdynasty#5]
Exceeded 80 columns.
https://github.com/PUP-BSIT/exercise-4-devdynasty/blob/1ee5b2f65291438387949eb50bc61419fe874126/src/app/parent/parent.component.html#L67
minus 1

------

Use guard clause.
https://github.com/PUP-BSIT/exercise-4-devdynasty/blob/1ee5b2f65291438387949eb50bc61419fe874126/src/app/parent/parent.component.ts#L62-L69
![image](https://github.com/PUP-BSIT/exercise-4-devdynasty/assets/76401444/ff9858b2-59a7-477b-a369-9585530c6136)
minus 1

------

Make these one liner statements.
https://github.com/PUP-BSIT/exercise-4-devdynasty/blob/1ee5b2f65291438387949eb50bc61419fe874126/src/app/parent/child/child.component.ts#L11-L16
![image](https://github.com/PUP-BSIT/exercise-4-devdynasty/assets/76401444/97d57716-3fed-401b-aab9-f002d915b6be)
minus 1

-------

Score 7/10. You can use a protection card here to reduce deduction. Just take a picture of your protection card and hand it over to me during f2f.

**Comment by Lopez-JhonLay** [comment]
Thank you sir, your feedback is noted. We will ensure to double check and apply it on our future exercises.
